M48
; DRILL file {KiCad 7.0.6} date Fri Nov 17 16:50:33 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-17T16:50:33-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0197
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
%
G90
G05
T1
X7.4803Y-4.5709
T2
X6.3949Y-2.6252
X6.6224Y-2.6252
T3
X6.1024Y-2.5591
X7.1654Y-5.6693
X8.8583Y-2.5591
X8.8583Y-5.6693
T0
M30
